version: '3.4'
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
volumes:
  binddnpdappnodeeth_data: {}
services:
  bind.dnp.dappnode.eth:
    build: ./build
    image: 'bind.dnp.dappnode.eth:0.2.2'
    container_name: DAppNodeCore-bind.dnp.dappnode.eth
    restart: always
    volumes:
      - 'binddnpdappnodeeth_data:/etc/bind'
    networks:
      network:
        ipv4_address: 172.33.1.2
    logging:
      driver: journald
