version: "3.4"
services:
  bind-slim.dnp.dappnode.eth:
    build: ./build
    image: "bind-slim.dnp.dappnode.eth:0.2.6"
    container_name: DAppNodeCore-bind-slim.dnp.dappnode.eth
    restart: always
    networks:
      dncore_network:
        ipv4_address: 172.33.1.2
    logging:
      driver: journald

networks:
  dncore_network:
    external: true
